# fly.toml app configuration file generated for malagamontes on 2025-01-22T13:13:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'malagamontes'
primary_region = 'mad'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  size = 'shared-cpu-1x'

[env]
  PORT = "8080"
  DATABASE_URL = "sqlite3:///data/production.sqlite3"

[processes]
  app = "./bin/rails server"

[deploy]
  release_command = "./bin/rails db:prepare"

